/* This file will be automatically generated by the build process */
/* Generated from src/main.tsx and all React components */

// Placeholder - this will be replaced by the actual React app bundle
console.log('Canvas by Recess Club - Loading...');

// This content will be replaced when running the extension build
document.addEventListener('DOMContentLoaded', () => {
  const root = document.getElementById('root');
  if (root) {
    root.innerHTML = '<div style="display: flex; align-items: center; justify-content: center; height: 100vh; font-family: system-ui;">Loading Canvas by Recess Club...</div>';
  }
});